#!/bin/sh

cd eval && ./clean && cd $SAFE_HOME
cd dynamic-shortcut && ./clean && cd $SAFE_HOME
cd tests/benchmarks/lodash4/diff-test && ./clean && cd $SAFE_HOME
cd tests/benchmarks/lodash4/ds-diff-test && ./clean && cd $SAFE_HOME
