a = []
_<>_print(a.length)
_<>_print(a.toString())
_<>_print(a.push())
_<>_print(a.length)
_<>_print(a.toString())
_<>_print(a.push(1))
_<>_print(a.length)
_<>_print(a.toString())
_<>_print(a.push("a","b"))
_<>_print(a.length)
_<>_print(a.toString())
_<>_print(a.push(1,2,3))
_<>_print(a.length)
_<>_print(a.toString())
