a = Array().concat(1, "a", ["b", 2])
_<>_print(a.length)
_<>_print(a.toString())
b = Array.prototype.concat(1, "a", ["b", 2])
_<>_print(b.length)
_<>_print(b.toString())
c = Array.prototype.concat()
_<>_print(c.length)
_<>_print(c.toString())
