a = new Array(1,2,3)
_<>_print(a.toString())
_<>_print(a.toString("::"))
_<>_print(a.join())
_<>_print(a.join("::"))
b = [1,2,3]
_<>_print(b.toString())
_<>_print(b.toString("::"))
_<>_print(b.join())
_<>_print(b.join("::"))
