a = ["a", "b", "c"]
_<>_print(a.length)
_<>_print(a.toString())
_<>_print(a.pop())
_<>_print(a.length)
_<>_print(a.toString())
_<>_print(a.pop())
_<>_print(a.length)
_<>_print(a.toString())
_<>_print(a.pop())
_<>_print(a.length)
_<>_print(a.toString())
_<>_print(a.pop())
_<>_print(a.length)
_<>_print(a.toString())
