a = Array()
_<>_print(a.length)
a = Array(42)
_<>_print(a.length)
a = Array("42")
_<>_print(a.length)
_<>_print(a[0])
a = Array(1,2)
_<>_print(a.length)
_<>_print(a[0])
_<>_print(a[1])
a = Array(1,2,3)
_<>_print(a.length)
_<>_print(a[0])
_<>_print(a[1])
_<>_print(a[2])
a[2]
