a = new Boolean(0)
_<>_print(typeof a)
_<>_print(a instanceof Boolean)
_<>_print(a)
a = new Boolean(1)
_<>_print(a)
a = new Boolean("")
_<>_print(a)
a = new Boolean("a")
_<>_print(a)
a = new Boolean(false)
_<>_print(a)
a = new Boolean(true)
_<>_print(a)
"PASS"
