a = new RegExp("\\d")
_<>_print(a.test("0"))
_<>_print(a.test("9"))
_<>_print(a.test("a"))
_<>_print(a.test("z"))
_<>_print(a.test("A"))
_<>_print(a.test("Z"))
_<>_print(a.test("_"))
_<>_print(a.test(" "))
a = new RegExp("\\D")
_<>_print(a.test("0"))
_<>_print(a.test("9"))
_<>_print(a.test("a"))
_<>_print(a.test("z"))
_<>_print(a.test("A"))
_<>_print(a.test("Z"))
_<>_print(a.test("_"))
_<>_print(a.test(" "))
a = new RegExp("\\s")
_<>_print(a.test("0"))
_<>_print(a.test("9"))
_<>_print(a.test("a"))
_<>_print(a.test("z"))
_<>_print(a.test("A"))
_<>_print(a.test("Z"))
_<>_print(a.test("_"))
_<>_print(a.test(" "))
a = new RegExp("\\S")
_<>_print(a.test("0"))
_<>_print(a.test("9"))
_<>_print(a.test("a"))
_<>_print(a.test("z"))
_<>_print(a.test("A"))
_<>_print(a.test("Z"))
_<>_print(a.test("_"))
_<>_print(a.test(" "))
a = new RegExp("\\w")
_<>_print(a.test("0"))
_<>_print(a.test("9"))
_<>_print(a.test("a"))
_<>_print(a.test("z"))
_<>_print(a.test("A"))
_<>_print(a.test("Z"))
_<>_print(a.test("_"))
_<>_print(a.test(" "))
a = new RegExp("\\W")
_<>_print(a.test("0"))
_<>_print(a.test("9"))
_<>_print(a.test("a"))
_<>_print(a.test("z"))
_<>_print(a.test("A"))
_<>_print(a.test("Z"))
_<>_print(a.test("_"))
_<>_print(a.test(" "))
"PASS"
