a = new RegExp("ab*c")
_<>_print(a.test("ac"))
_<>_print(a.test("abc"))
_<>_print(a.test("abbc"))
_<>_print(a.test("abbbc"))
a = new RegExp("ab+c")
_<>_print(a.test("ac"))
_<>_print(a.test("abc"))
_<>_print(a.test("abbc"))
_<>_print(a.test("abbbc"))
a = new RegExp("ab?c")
_<>_print(a.test("ac"))
_<>_print(a.test("abc"))
_<>_print(a.test("abbc"))
_<>_print(a.test("abbbc"))
a = new RegExp("ab{2}c")
_<>_print(a.test("ac"))
_<>_print(a.test("abc"))
_<>_print(a.test("abbc"))
_<>_print(a.test("abbbc"))
a = new RegExp("ab{1,}c")
_<>_print(a.test("ac"))
_<>_print(a.test("abc"))
_<>_print(a.test("abbc"))
_<>_print(a.test("abbbc"))
a = new RegExp("ab{1,2}c")
_<>_print(a.test("ac"))
_<>_print(a.test("abc"))
_<>_print(a.test("abbc"))
_<>_print(a.test("abbbc"))
"PASS"
