(function(){var f=parseFloat("0.01"),h=isNaN(f)||1<f||0>f?0:f;var k=function(a,b){for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.call(null,a[d],d,a)};var l=function(a){this.b=[];this.a={};for(var b=0,d=arguments.length;b<d;++b)this.a[arguments[b]]=""},n=function(){var a=m,b=["317150500","317150501"],d;if(d=a.a.hasOwnProperty(1)&&""==a.a[1])d=!(1E-4>Math.random())&&Math.random()<h;d&&(b=b[Math.floor(Math.random()*b.length)],""!=b&&a.a.hasOwnProperty(1)&&(a.a[1]=b))};l.prototype.c=function(a){return this.a.hasOwnProperty(a)?this.a[a]:""};l.prototype.geil=l.prototype.c;
var p=function(){var a=m,b=[];k(a.a,function(a){""!=a&&b.push(a)});return 0<a.b.length&&0<b.length?a.b.join(",")+","+b.join(","):a.b.join(",")+b.join(",")};var m,q="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_remarketing_only google_remarketing_for_search google_conversion_items google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_is_call google_conversion_page_url".split(" ");
function r(a){return null!=a?escape(a.toString()):""}function s(a,b){var d=r(b);if(""!=d){var c=r(a);if(""!=c)return"&".concat(c,"=",d)}return""}function t(a){var b=typeof a;return null==a||"object"==b||"function"==b?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")}
function u(a){var b;if((a=a.google_custom_params)&&"object"==typeof a&&"function"!=typeof a.join){var d=[];for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b];if(c&&"function"==typeof c.join){for(var e=[],g=0;g<c.length;++g){var x=t(c[g]);null!=x&&e.push(x)}c=0==e.length?null:e.join(",")}else c=t(c);(e=t(b))&&null!=c&&d.push(e+"="+c)}b=d.join(";")}else b="";return""==b?"":"&".concat("data=",encodeURIComponent(b))}
function v(a){return"number"!=typeof a&&"string"!=typeof a?"":r(a.toString())}function w(a){if(!a)return"";a=a.google_conversion_items;if(!a)return"";for(var b=[],d=0,c=a.length;d<c;d++){var e=a[d],g=[];e&&(g.push(v(e.value)),g.push(v(e.quantity)),g.push(v(e.item_id)),g.push(v(e.adwords_grouping)),g.push(v(e.sku)),b.push("("+g.join("*")+")"))}return 0<b.length?"&item="+b.join(""):""}
function y(a,b,d){var c=[];if(a){var e=a.screen;e&&(c.push(s("u_h",e.height)),c.push(s("u_w",e.width)),c.push(s("u_ah",e.availHeight)),c.push(s("u_aw",e.availWidth)),c.push(s("u_cd",e.colorDepth)));a.history&&c.push(s("u_his",a.history.length))}d&&"function"==typeof d.getTimezoneOffset&&c.push(s("u_tz",-d.getTimezoneOffset()));b&&("function"==typeof b.javaEnabled&&c.push(s("u_java",b.javaEnabled())),b.plugins&&c.push(s("u_nplug",b.plugins.length)),b.mimeTypes&&c.push(s("u_nmime",b.mimeTypes.length)));
return c.join("")}function z(a,b,d){var c="";if(b){var c=c+s("ref",null!=b.referrer?b.referrer.toString().substring(0,256):""),e;if(a.top==a)e=0;else if(b=a.location.ancestorOrigins)e=b[b.length-1]==a.location.origin?1:2;else{b=a.top;try{e=!!b.location.href||""===b.location.href}catch(g){e=!1}e=e?1:2}b="";b=d?d:1==e?a.top.location.href:a.location.href;c+=s("url",null!=b?b.toString().substring(0,256):"");c+=s("frm",e)}return c}
function A(a){return a&&a.location&&a.location.protocol&&"https:"==a.location.protocol.toString().toLowerCase()?"https:":"http:"}function B(a){return a.google_remarketing_only?"googleads.g.doubleclick.net":a.google_conversion_domain||"www.googleadservices.com"}
function C(a,b,d,c){var e="/?";"landing"==c.google_conversion_type&&(e="/extclk?");var e=A(a)+"//"+B(c)+"/pagead/"+[c.google_remarketing_only?"viewthroughconversion/":"conversion/",r(c.google_conversion_id),e,"random=",r(c.google_conversion_time)].join(""),g;n:{g=c.google_conversion_language;if(null!=g){g=g.toString();if(2==g.length){g=s("hl",g);break n}if(5==g.length){g=s("hl",g.substring(0,2))+s("gl",g.substring(3,5));break n}}g=""}return e+=[s("cv",c.google_conversion_js_version),s("fst",c.google_conversion_first_time),
s("num",c.google_conversion_snippets),s("fmt",c.google_conversion_format),s("value",c.google_conversion_value),s("label",c.google_conversion_label),s("oid",c.google_conversion_order_id),s("bg",c.google_conversion_color),g,s("guid","ON"),s("disvt",c.google_disable_viewthrough),s("is_call",c.google_is_call),w(c),y(a,b,c.google_conversion_date),z(a,d,c.google_conversion_page_url),u(c),c.google_remarketing_for_search&&!c.google_conversion_domain?"&srr=n":"",s("eid",p())].join("")}
function D(){var a=E,b=F,d=A(a)+"//www.google.com/ads/user-lists/"+[r(b.google_conversion_id),"/?random=",Math.floor(1E9*Math.random())].join("");return d+=[s("label",b.google_conversion_label),s("fmt","3"),z(a,document,b.google_conversion_page_url)].join("")}
function G(){var a=E,b=navigator,d=document,c=E;3!=c.google_conversion_format||(c.google_remarketing_only||c.google_conversion_domain)||m&&n();var e=m?m.c(1):"",b=C(a,b,d,c),d=function(a,b,c){return'<img height="'+c+'" width="'+b+'" border="0" src="'+a+'" />'};return 0==c.google_conversion_format&&null==c.google_conversion_domain?'<a href="'+(A(a)+"//services.google.com/sitestats/"+({ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,
ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1}[c.google_conversion_language]?c.google_conversion_language+".html":"en_US.html")+"?cid="+r(c.google_conversion_id))+'" target="_blank">'+d(b,135,27)+"</a>":1<c.google_conversion_snippets||3==c.google_conversion_format?"317150501"==e?d(b,1,1)+('<script src="'+b.replace(/(&|\?)fmt=3(&|$)/,"$1fmt=4&adtest=on$2")+'">\x3c/script>'):d(b,1,1):'<iframe name="google_conversion_frame" width="'+(2==c.google_conversion_format?
200:300)+'" height="'+(2==c.google_conversion_format?26:13)+'" src="'+b+'" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">'+d(b.replace(/\?random=/,"?frame=0&random="),1,1)+"</iframe>"}function H(){return new Image}function I(){var a=F,b=D(),d=H;"function"===typeof a.opt_image_generator&&(d=a.opt_image_generator);a=d();b+=s("async","1");a.src=b;a.onload=function(){}};var E=window;
if(E)if(null!=/[\?&;]google_debug/.exec(document.URL)){var J=E,K=document.getElementsByTagName("head")[0];K||(K=document.createElement("head"),document.getElementsByTagName("html")[0].insertBefore(K,document.getElementsByTagName("body")[0]));var L=document.createElement("script");L.src=A(window)+"//"+B(J)+"/pagead/conversion_debug_overlay.js";K.appendChild(L)}else{try{var M;var N=E;"landing"==N.google_conversion_type||!N.google_conversion_id||N.google_remarketing_only&&N.google_disable_viewthrough?M=
!1:(N.google_conversion_date=new Date,N.google_conversion_time=N.google_conversion_date.getTime(),N.google_conversion_snippets="number"==typeof N.google_conversion_snippets&&0<N.google_conversion_snippets?N.google_conversion_snippets+1:1,"number"!=typeof N.google_conversion_first_time&&(N.google_conversion_first_time=N.google_conversion_time),N.google_conversion_js_version="7",0!=N.google_conversion_format&&(1!=N.google_conversion_format&&2!=N.google_conversion_format&&3!=N.google_conversion_format)&&
(N.google_conversion_format=1),m=new l(1),M=!0);if(M&&(document.write(G()),E.google_remarketing_for_search&&!E.google_conversion_domain)){var F=E;I()}}catch(O){}for(var P=E,Q=0;Q<q.length;Q++)P[q[Q]]=null};})();
